# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Test Next.js

on:
  # Runs on pushes targeting the default branch
  push:
  #  branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

env:
  CYPRESS_CREDENTIALS_USER: ${{ secrets.CYPRESS_CREDENTIALS_USER }}
  CYPRESS_CREDENTIALS_PW: ${{ secrets.CYPRESS_CREDENTIALS_PW }}
  CYPRESS_GITHUB_USER: ${{ secrets.CYPRESS_GITHUB_USER }}
  CYPRESS_GITHUB_PW: ${{ secrets.CYPRESS_GITHUB_PW }}
  CYPRESS_FACEBOOK_USER: ${{ secrets.CYPRESS_FACEBOOK_USER }}
  CYPRESS_FACEBOOK_PW: ${{ secrets.CYPRESS_FACEBOOK_PW }}
  CYPRESS_COOKIE_NAME: ${{ secrets.CYPRESS_COOKIE_NAME }}
  CYPRESS_SITE_NAME: ${{ secrets.CYPRESS_SITE_NAME }}

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.17.0-chrome106
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false
          build: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: .next

  cypress-run:
    runs-on: ubuntu-latest
    needs: install
    container: cypress/browsers:node16.17.0-chrome106
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: .next

      - name: Show Cypress information ℹ️
        run: npx cypress info

      - name: Verify Cypress can run 🏃‍♂️
        run: npx cypress verify

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          start: npm run start
